export const ticket = {
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    PENDING: "PENDING"
}


export const STATUS_CODES = {
    ok: 200,
    INTERNAL_SERVER_ERROR: 500,
    CREATED: 201,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
    UNPROCESSABLE_ENTITY: 422,
    BAD_REQUEST: 400,
    ALLREADY_EXIST: 409,
    FORBIDDEN: 403,
    GONE: 410,
    PAYMENT_REQUIRED: 402
}
